### ISSUE TITLE
Author Name without link and instead of the username the full name

### ISSUE THREAD

**Issue by ak1982** [mittwald/typo3_forum#207]
Hello,

is it possible to unlink the author name and also to show the full name of the author?

Best regards
Andreas

**Comment by pstranghoener** [comment]
At the moment thats not possible. If you want it you can develop it for and give it back to us via an pull request.

**Comment by pstranghoener** [comment]
That issue is very special could i close that? @ak1982

**Comment by pstranghoener** [comment]
I will close that ticket because of no reaction of the author.

**Comment by mocsap** [comment]
Is there any simple way to change the post authors from username into full names with first and lastname? It is really confusing with the usernames.

**Comment by velletti** [comment]
1. Removing the link should be easy : remove typoscript setup  for 

plugin.tx_typo3forum.settingspids.UserShow = 0  # any non existing page

2. Changing Username to First _ Lastname should be done in Template 

https://github.com/mittwald/typo3_forum/blob/develop/Resources/Private/Partials/Standard/User/InformationRow.html

Overwrite that template and change code to something like {user.firstname} {user.lastname} instead of {user.username}

**Comment by mocsap** [comment]
Thank you for this valuable hint. I was able to change some templates using your suggestion. And it works! Hovewer your hint could not be applied for the topic author field. The author field is delivered from the _topic.author_ which probably is delivered from the typo3 users table. Nevertheless thanks for your post, it helped me a lot to understand the code structure.

**Comment by velletti** [comment]
I have also a partial called Ajax/PostSummery containg the username and link to the user

**Comment by mocsap** [comment]
Well, I'm not a Typo3 developer. Could you explain this, please?
