### ISSUE TITLE
Subscription and Readstatus

### ISSUE THREAD

**Issue by kaialt** [mittwald/typo3_forum#250]
I don't get it solved:

1. Forums are always marked as "new". Read Topics works.
2. Subscription to Forum doesn't work. It seams that the relation in tx_typo3forum_domain_model_user_forumsubscription is insert correctly, but no mail will be sent.
3. Subscripe or unsubscripe to Topics  is only working with the solution in closed issues #107. 

Any hints for me? Someboby else who have the same problems in the Master- and in the Developversion?

**Comment by sigma67** [comment]
As for 2, the mail sending part is not implemented. You'll have to use code from open issue #184 .

**Comment by mgrundkoetter** [comment]
I have the same issue with the subscription status. Problem there is, the `` inherits from the fluid base `IfViewHelper`. So either `render()` AND `renderStatic()` have to be implemented (which is not done in all those helpers in typo3_forum) OR instead of overwriting the `render()` method, just the static `evaluateCondition()` has to be overwritten.
Description also on https://stackoverflow.com/questions/34729014/typo3-ver-7-6-2-condition-viewhelpers-evaluated-only-once.

**Comment by mvolland** [comment]
> Forums are always marked as "new". Read Topics works.

I have the same problem. Any solution for this?

**Comment by sgrossberndt** [comment]
https://github.com/mittwald/typo3_forum/pull/305 adds notifications for forum subscriptions

The `IfSubscribedViewHelper ` was fixed in https://github.com/mittwald/typo3_forum/commit/b5accfb69db1bdcf704a63135c7e5ace42cd6f47

Forums are always marked as "new" if they do not contain any topics.
