### ISSUE TITLE
Release Version 1.1.1

### ISSUE THREAD

**Issue by DavidBruchmann** [mittwald/typo3_forum#263]
Why Release Version 1.1.1 is not available here?  
https://typo3.org/extensions/repository/download/typo3_forum/1.1.1/zip/

**Comment by pstranghoener** [comment]
Because its an Security Release.

**Comment by DavidBruchmann** [comment]
BUFFER OVERFLOW

**Comment by schams-net** [comment]
@pstranghoener could you please shed some light on the logic, why you do not release a **fixed** version in Git (due to security issues)?

This does not make much sense to me, given this version has been uploaded to the [TER](https://extensions.typo3.org) and a security advice ([TYPO3-EXT-SA-2019-002](https://typo3.org/security/advisory/typo3-ext-sa-2019-002/)) has been released by the TYPO3 Security Team three weeks ago.
